club_names:
  ' FC$': ''
  'AFC ': ''
  'Queens Park Rangers': 'QPR'
  'Manchester City': 'Man City'
  'Manchester United': 'Man Utd'
  'Nottingham Forest': 'Nottm Forest'
  'Leicester City': 'Leicester'
  'Newcastle United': 'Newcastle'
  'Leeds United': 'Leeds'
  'Norwich City': 'Norwich'
  'Sheffield United': 'Sheff Utd'
  'Sheffield Wednesday': 'Sheff Wed'
  'Coventry City': 'Coventry'
  'West Ham United': 'West Ham'
  'Wolverhampton Wanderers': 'Wolves'
  'West Bromwich Albion': 'West Brom'
  ' AFC': ''
  ' Wanderers': ''
  ' Rovers': ''
  ' & Hove Albion': ''
  ' Athletic': ''
  ' County': ''
  ' Town': ''
  'Wimbledon FC (- 2004)': 'Wimbledon FC'
  ' Hotspur': ''
  'Birmingham City': 'Birmingham'
  'Swansea City': 'Swansea'
  'Bradford City': 'Bradford'
  'Brentford City': 'Brentford'